### ISSUE TITLE
Ruleta Rusa

### ISSUE THREAD

**Issue by JesusGarciaMinas** [oktorok/remibot#2]
Opción 1: El bot echará a un usuario con el comando .RussianRevolver con una probabilidad de 1 / 6

Opción 2: El bot echará a uno de los usuarios del canal en el que el usuario ejecute el comando. Si el usuario no está en ningún canal, este no hará nada.

**Comment by JesusGarciaMinas** [comment]
Cuando no se está en un canal de voz el comando sigue funcionando y realiza cosas extrañas cuando acierta. Cambiar funcionalidad para que no funcione si no se está en un canal o que realice otra acción

**Comment by JesusGarciaMinas** [comment]
Cuando se intenta echar a varias personas a la vez se dejan creados los canales de voz jail

**Comment by oktorok** [comment]
Arreglado Russian revolver, anyade otro issue con metodo de reproduccion sobre el bug de jail
