### ISSUE TITLE
Sustituir a Nadeko

### ISSUE THREAD

**Issue by JesusGarciaMinas** [oktorok/remibot#8]
Se implementarán las funcionalidades de Nadeko para evitar duplicado de bots en el servidor

**Comment by oktorok** [comment]
Que funcionalidades?

**Comment by JesusGarciaMinas** [comment]
Aquellas que sean utiles y utilizadas a menudo en el servidor

**Comment by cesaralvarez97** [comment]
Se han añadido los mute y unmute, otras a añadir serian el softban, ban y unban. Me pondre a ello

**Comment by oktorok** [comment]
Cierro por inactividad
